import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <title>My first app with Next.js</title>
      <body>
        <header>
          <nav>
            <ul>
              <li>Home</li>
            </ul>
          </nav>
        </header>
        {children}</body>
    </html>
  )
}
